---

EMAIL_RELAY: localhost
EMAIL_FROM: jwoolf@purestorage.com
EMAIL_SUBJECT: 'Pure Storage Report'
EMAIL_TEXT: 'This is the text in the email\n\nLets see if this works.'

ARRAYS:
  -
    name: 'TestArray1'
    address: '10.21.167.15'
    token: 'd6df8f37-e6b7-7d93-029b-d94952b6020c'
  -
    name: "TestArray2"
    address: '10.21.167.70'
    token: 'a222a925-8fc7-b6b4-f29d-cbfa9f8952a2'